name: Secrets Scan

on:
  pull_request:
    branches:
      - main

jobs:
  secrets:
    name: Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Secret Scanner
        uses: secret-scanner/action@0.0.2
