name: Snyk Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Repositorio
      - uses: action/checkout@v3

      - name: Install/Setup Python
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      
      - name: Instalo dependencias
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.10@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high